version: "3"
services:
  web-app:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/mari/Documentos/2021/NSQL - DOCKER/BD-NSQL/Db-docker/api:/api
    depends_on:
      - "db-redis"

  db-redis:
    image: redis
    ports:
      - "6379:6379"