version: "3"
services:
  web-app:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - /home/mari/Descargas/BD-NSQL-main/Db-docker/api:/api
    depends_on:
      - "db-redis"

  db-redis:
    image: redis
    ports:
      - "6380:6379"
    container_name: db-redis